cluster_formation.peer_discovery_backend = classic_config
cluster_formation.classic_config.nodes.1 = rabbit@security-rabbitmq-1
cluster_formation.classic_config.nodes.2 = rabbit@security-rabbitmq-2
cluster_formation.classic_config.nodes.3 = rabbit@security-rabbitmq-3
cluster_formation.node_cleanup.only_log_warning = true
cluster_formation.target_cluster_size_hint = 3
listeners.tcp.default = 5672
management.tcp.port = 15672
log.console = true
log.console.level = info
auth_backends.1 = ldap
auth_ldap.servers.1 = ldap-directory
auth_ldap.port = 1636
auth_ldap.user_dn_pattern = cn=${username},ou=users,dc=atlas,dc=local
auth_ldap.use_ssl = true
auth_ldap.ssl_options.verify = verify_peer
auth_ldap.ssl_options.cacertfile = /etc/rabbitmq/ldap-ca/ca.crt
auth_ldap.log = true
