cluster_formation.peer_discovery_backend = classic_config
cluster_formation.classic_config.nodes.1 = rabbit@oauth-rabbitmq-1
cluster_formation.classic_config.nodes.2 = rabbit@oauth-rabbitmq-2
cluster_formation.classic_config.nodes.3 = rabbit@oauth-rabbitmq-3
cluster_formation.node_cleanup.only_log_warning = true
cluster_formation.target_cluster_size_hint = 3
listeners.tcp.default = 5672
management.tcp.port = 15672
log.console = true
log.console.level = info
auth_backends.1 = oauth2
auth_oauth2.resource_server_id = rabbitmq
auth_oauth2.issuer = https://keycloak:8443/realms/rabbitmq
auth_oauth2.https.cacertfile = /etc/rabbitmq/oauth-ca/ca.crt
auth_oauth2.https.peer_verification = verify_peer
auth_oauth2.https.hostname_verification = wildcard
auth_oauth2.preferred_username_claims.1 = preferred_username
management.oauth_enabled = true
management.oauth_client_id = rabbitmq-management
management.oauth_scopes = openid profile rabbitmq.tag:management
management.oauth_disable_basic_auth = true
